import {
  BookOpen,
  NotebookPen,
  Pencil,
  GraduationCap,
  Languages,
  Calculator,
  FlaskConical,
  Music,
  Headphones,
  Palette,
  Camera,
  Code,
  Briefcase,
  Mail,
  Phone,
  CalendarDays,
  Clock,
  ListChecks,
  Target,
  Flag,
  Star,
  Heart,
  Activity,
  Dumbbell,
  Bike,
  Footprints,
  Coffee,
  Utensils,
  Droplets,
  Moon,
  Sun,
  House,
  ShoppingBag,
  Wallet,
  Plane,
  Train,
  MapPin,
  Leaf,
  Flower2,
  Lightbulb,
  Sparkles,
  Circle,
} from "lucide-react";

export const symbolGroups = [
  "전체",
  "학습·작업",
  "일정·목표",
  "생활·건강",
  "취미·이동",
];
const groups = [
  [
    ["book", BookOpen, "독서 책"],
    ["note", NotebookPen, "노트 메모"],
    ["pencil", Pencil, "쓰기 연필"],
    ["education", GraduationCap, "교육 공부"],
    ["language", Languages, "언어"],
    ["math", Calculator, "수학 계산"],
    ["science", FlaskConical, "과학 실험"],
    ["code", Code, "코딩 개발"],
    ["work", Briefcase, "업무 일"],
    ["mail", Mail, "이메일"],
    ["idea", Lightbulb, "아이디어"],
  ],
  [
    ["calendar", CalendarDays, "달력 일정"],
    ["clock", Clock, "시간"],
    ["checklist", ListChecks, "체크 목록"],
    ["target", Target, "목표"],
    ["flag", Flag, "깃발 마커"],
    ["star", Star, "별 중요"],
    ["sparkles", Sparkles, "반짝임"],
    ["circle", Circle, "원 기본"],
  ],
  [
    ["heart", Heart, "마음 건강"],
    ["activity", Activity, "활동"],
    ["exercise", Dumbbell, "운동"],
    ["walk", Footprints, "걷기 산책"],
    ["coffee", Coffee, "커피 휴식"],
    ["meal", Utensils, "식사"],
    ["water", Droplets, "물"],
    ["moon", Moon, "밤 수면"],
    ["sun", Sun, "아침 햇빛"],
    ["home", House, "집"],
    ["shopping", ShoppingBag, "쇼핑"],
    ["wallet", Wallet, "돈 지출"],
    ["phone", Phone, "전화"],
  ],
  [
    ["music", Music, "음악"],
    ["headphones", Headphones, "듣기"],
    ["art", Palette, "미술"],
    ["camera", Camera, "사진"],
    ["bike", Bike, "자전거"],
    ["plane", Plane, "여행 비행기"],
    ["train", Train, "기차"],
    ["location", MapPin, "장소"],
    ["leaf", Leaf, "자연"],
    ["flower", Flower2, "꽃"],
  ],
];
export const symbols = groups.flatMap((items, i) =>
  items.map(([name, Icon, label]) => ({
    name,
    Icon,
    label,
    group: symbolGroups[i + 1],
  })),
);
export const symbolMap = Object.fromEntries(
  symbols.map((item) => [item.name, item]),
);
export const defaultSymbolColor = "#64748b";
