import { Notebook, NotepadText, BookMarked, BookCopy, BookHeadphones, BookKey, BookLock, BookType, BookUser, BookA, FileCheck, FileCode, FileImage, FileSpreadsheet, FileSearch, Files, FolderCheck, FolderKanban, Database, Server, HardDrive, Laptop, Mouse, Tablet, Smartphone, ScanText, ScanLine, Network, Workflow, GitBranch, Binary, Braces, Brackets, Regex, Component, Layers, Paperclip, Highlighter, Eraser, Scissors, StickyNote, ChartPie, ChartLine, ChartBar, LightbulbOff, CalendarPlus, CalendarHeart, CalendarSearch, CalendarX, CalendarSync, CalendarFold, ClockCheck, ClockAlert, ClockArrowUp, ClockArrowDown, Hourglass, TimerReset, TimerOff, AlarmClockCheck, AlarmClockOff, ListOrdered, ListFilter, ListRestart, ClipboardCheck, ClipboardList, ClipboardPen, Check, CheckCircle2, BadgeCheck, Badge, Crown, Gem, Diamond, Flame, Zap, Goal, Route, Signpost, Focus, ScanEye, FlagTriangleRight, BookmarkCheck, BookmarkPlus, BellRing, BellOff, Infinity, RotateCcw, Forward, FastForward, Pause, Banana, Carrot, Cherry, Citrus, Grape, Beef, Fish, Egg, Milk, Wheat, Sandwich, Pizza, CakeSlice, IceCreamBowl, Cookie, Candy, Popcorn, CupSoda, GlassWater, Wine, Beer, CookingPot, Microwave, Refrigerator, FlameKindling, Armchair, Sofa, Shirt, Glasses, Watch, ShoppingCart, CreditCard, Coins, Landmark, KeyRound, LockKeyhole, HeartPulse, Bandage, Syringe, Thermometer, Weight, Scale, Accessibility, PersonStanding, Dog, Cat, Rabbit, Bird, Turtle, Snail, Bug, PawPrint, Feather, Flower, Sprout, TreeDeciduous, Clover, Cloud, CloudRain, CloudSnow, Snowflake, Wind, Rainbow, SunSnow, MountainSnow, Earth, Orbit, Telescope, Satellite, CameraOff, Video, Clapperboard, Mic, Drum, Piano, Disc3, Music2, AudioLines, Podcast, PaintBucket, Brush, Origami, Puzzle, Dices, Spade, FerrisWheel, Sailboat, Anchor, Kayak, Caravan, Backpack, Luggage, Hotel, Building2, Castle, Church, Store, Fuel, ParkingCircle, TrafficCone, TrainFront } from "lucide-react";

export const symbolExtras = [
  [
    ["extra-notebook", Notebook, "공책", "Notebook"],
    ["extra-notepad-text", NotepadText, "메모장", "Notepad Text"],
    ["extra-book-marked", BookMarked, "책갈피책", "Book Marked"],
    ["extra-book-copy", BookCopy, "복사교재", "Book Copy"],
    ["extra-book-headphones", BookHeadphones, "오디오북", "Book Headphones"],
    ["extra-book-key", BookKey, "해설서", "Book Key"],
    ["extra-book-lock", BookLock, "비밀노트", "Book Lock"],
    ["extra-book-type", BookType, "사전", "Book Type"],
    ["extra-book-user", BookUser, "학생기록", "Book User"],
    ["extra-book-a", BookA, "알파벳", "Book A"],
    ["extra-file-check", FileCheck, "검토완료", "File Check"],
    ["extra-file-code", FileCode, "소스코드", "File Code"],
    ["extra-file-image", FileImage, "이미지파일", "File Image"],
    ["extra-file-spreadsheet", FileSpreadsheet, "스프레드시트", "File Spreadsheet"],
    ["extra-file-search", FileSearch, "자료검색", "File Search"],
    ["extra-files", Files, "파일묶음", "Files"],
    ["extra-folder-check", FolderCheck, "프로젝트완료", "Folder Check"],
    ["extra-folder-kanban", FolderKanban, "프로젝트관리", "Folder Kanban"],
    ["extra-database", Database, "데이터베이스", "Database"],
    ["extra-server", Server, "서버", "Server"],
    ["extra-hard-drive", HardDrive, "저장장치", "Hard Drive"],
    ["extra-laptop", Laptop, "노트북컴퓨터", "Laptop"],
    ["extra-mouse", Mouse, "마우스", "Mouse"],
    ["extra-tablet", Tablet, "태블릿", "Tablet"],
    ["extra-smartphone", Smartphone, "스마트폰", "Smartphone"],
    ["extra-scan-text", ScanText, "문자인식", "Scan Text"],
    ["extra-scan-line", ScanLine, "스캔", "Scan Line"],
    ["extra-network", Network, "네트워크", "Network"],
    ["extra-workflow", Workflow, "작업흐름", "Workflow"],
    ["extra-git-branch", GitBranch, "코드분기", "Git Branch"],
    ["extra-binary", Binary, "이진수", "Binary"],
    ["extra-braces", Braces, "프로그래밍", "Braces"],
    ["extra-brackets", Brackets, "문법", "Brackets"],
    ["extra-regex", Regex, "정규식", "Regex"],
    ["extra-component", Component, "컴포넌트", "Component"],
    ["extra-layers", Layers, "레이어", "Layers"],
    ["extra-paperclip", Paperclip, "첨부", "Paperclip"],
    ["extra-highlighter", Highlighter, "형광펜", "Highlighter"],
    ["extra-eraser", Eraser, "지우개", "Eraser"],
    ["extra-scissors", Scissors, "가위", "Scissors"],
    ["extra-sticky-note", StickyNote, "포스트잇", "Sticky Note"],
    ["extra-chart-pie", ChartPie, "원형차트", "Chart Pie"],
    ["extra-chart-line", ChartLine, "선형차트", "Chart Line"],
    ["extra-chart-bar", ChartBar, "막대그래프", "Chart Bar"],
    ["extra-lightbulb-off", LightbulbOff, "아이디어휴식", "Lightbulb Off"]
  ],
  [
    ["extra-calendar-plus", CalendarPlus, "일정추가", "Calendar Plus"],
    ["extra-calendar-heart", CalendarHeart, "특별한날", "Calendar Heart"],
    ["extra-calendar-search", CalendarSearch, "일정검색", "Calendar Search"],
    ["extra-calendar-x", CalendarX, "일정취소", "Calendar X"],
    ["extra-calendar-sync", CalendarSync, "일정조정", "Calendar Sync"],
    ["extra-calendar-fold", CalendarFold, "월간계획", "Calendar Fold"],
    ["extra-clock-check", ClockCheck, "시간준수", "Clock Check"],
    ["extra-clock-alert", ClockAlert, "시간주의", "Clock Alert"],
    ["extra-clock-arrow-up", ClockArrowUp, "시간추가", "Clock Arrow Up"],
    ["extra-clock-arrow-down", ClockArrowDown, "시간단축", "Clock Arrow Down"],
    ["extra-hourglass", Hourglass, "모래시계", "Hourglass"],
    ["extra-timer-reset", TimerReset, "타이머재시작", "Timer Reset"],
    ["extra-timer-off", TimerOff, "타이머종료", "Timer Off"],
    ["extra-alarm-clock-check", AlarmClockCheck, "알람확인", "Alarm Clock Check"],
    ["extra-alarm-clock-off", AlarmClockOff, "알람끄기", "Alarm Clock Off"],
    ["extra-list-ordered", ListOrdered, "순서목록", "List Ordered"],
    ["extra-list-filter", ListFilter, "목록분류", "List Filter"],
    ["extra-list-restart", ListRestart, "다시시작", "List Restart"],
    ["extra-clipboard-check", ClipboardCheck, "점검완료", "Clipboard Check"],
    ["extra-clipboard-list", ClipboardList, "체크리스트", "Clipboard List"],
    ["extra-clipboard-pen", ClipboardPen, "계획작성", "Clipboard Pen"],
    ["extra-check", Check, "확인", "Check"],
    ["extra-check-circle2", CheckCircle2, "성공확인", "Check Circle2"],
    ["extra-badge-check", BadgeCheck, "인증", "Badge Check"],
    ["extra-badge", Badge, "배지", "Badge"],
    ["extra-crown", Crown, "최고", "Crown"],
    ["extra-gem", Gem, "보석", "Gem"],
    ["extra-diamond", Diamond, "다이아몬드", "Diamond"],
    ["extra-flame", Flame, "열정", "Flame"],
    ["extra-zap", Zap, "빠른실행", "Zap"],
    ["extra-goal", Goal, "목표달성", "Goal"],
    ["extra-route", Route, "경로계획", "Route"],
    ["extra-signpost", Signpost, "방향표지", "Signpost"],
    ["extra-focus", Focus, "집중", "Focus"],
    ["extra-scan-eye", ScanEye, "집중관찰", "Scan Eye"],
    ["extra-flag-triangle-right", FlagTriangleRight, "출발깃발", "Flag Triangle Right"],
    ["extra-bookmark-check", BookmarkCheck, "저장완료", "Bookmark Check"],
    ["extra-bookmark-plus", BookmarkPlus, "저장추가", "Bookmark Plus"],
    ["extra-bell-ring", BellRing, "알림울림", "Bell Ring"],
    ["extra-bell-off", BellOff, "알림끄기", "Bell Off"],
    ["extra-infinity", Infinity, "꾸준함", "Infinity"],
    ["extra-rotate-ccw", RotateCcw, "다시도전", "Rotate Ccw"],
    ["extra-forward", Forward, "전진", "Forward"],
    ["extra-fast-forward", FastForward, "빠르게진행", "Fast Forward"],
    ["extra-pause", Pause, "잠깐멈춤", "Pause"]
  ],
  [
    ["extra-banana", Banana, "바나나", "Banana"],
    ["extra-carrot", Carrot, "당근", "Carrot"],
    ["extra-cherry", Cherry, "체리", "Cherry"],
    ["extra-citrus", Citrus, "감귤", "Citrus"],
    ["extra-grape", Grape, "포도", "Grape"],
    ["extra-beef", Beef, "고기", "Beef"],
    ["extra-fish", Fish, "생선", "Fish"],
    ["extra-egg", Egg, "달걀", "Egg"],
    ["extra-milk", Milk, "우유", "Milk"],
    ["extra-wheat", Wheat, "곡물", "Wheat"],
    ["extra-sandwich", Sandwich, "샌드위치", "Sandwich"],
    ["extra-pizza", Pizza, "피자", "Pizza"],
    ["extra-cake-slice", CakeSlice, "케이크", "Cake Slice"],
    ["extra-ice-cream-bowl", IceCreamBowl, "아이스크림", "Ice Cream Bowl"],
    ["extra-cookie", Cookie, "쿠키", "Cookie"],
    ["extra-candy", Candy, "사탕", "Candy"],
    ["extra-popcorn", Popcorn, "팝콘", "Popcorn"],
    ["extra-cup-soda", CupSoda, "음료", "Cup Soda"],
    ["extra-glass-water", GlassWater, "물마시기", "Glass Water"],
    ["extra-wine", Wine, "와인", "Wine"],
    ["extra-beer", Beer, "맥주", "Beer"],
    ["extra-cooking-pot", CookingPot, "요리", "Cooking Pot"],
    ["extra-microwave", Microwave, "전자레인지", "Microwave"],
    ["extra-refrigerator", Refrigerator, "냉장고", "Refrigerator"],
    ["extra-flame-kindling", FlameKindling, "불피우기", "Flame Kindling"],
    ["extra-armchair", Armchair, "휴식", "Armchair"],
    ["extra-sofa", Sofa, "소파", "Sofa"],
    ["extra-shirt", Shirt, "옷", "Shirt"],
    ["extra-glasses", Glasses, "안경", "Glasses"],
    ["extra-watch", Watch, "손목시계", "Watch"],
    ["extra-shopping-cart", ShoppingCart, "장보기", "Shopping Cart"],
    ["extra-credit-card", CreditCard, "카드결제", "Credit Card"],
    ["extra-coins", Coins, "동전", "Coins"],
    ["extra-landmark", Landmark, "은행", "Landmark"],
    ["extra-key-round", KeyRound, "열쇠", "Key Round"],
    ["extra-lock-keyhole", LockKeyhole, "잠금", "Lock Keyhole"],
    ["extra-heart-pulse", HeartPulse, "심박수", "Heart Pulse"],
    ["extra-bandage", Bandage, "붕대", "Bandage"],
    ["extra-syringe", Syringe, "주사", "Syringe"],
    ["extra-thermometer", Thermometer, "체온계", "Thermometer"],
    ["extra-weight", Weight, "체중", "Weight"],
    ["extra-scale", Scale, "균형", "Scale"],
    ["extra-accessibility", Accessibility, "스트레칭", "Accessibility"],
    ["extra-person-standing", PersonStanding, "바른자세", "Person Standing"]
  ],
  [
    ["extra-dog", Dog, "강아지", "Dog"],
    ["extra-cat", Cat, "고양이", "Cat"],
    ["extra-rabbit", Rabbit, "토끼", "Rabbit"],
    ["extra-bird", Bird, "새", "Bird"],
    ["extra-turtle", Turtle, "거북이", "Turtle"],
    ["extra-snail", Snail, "달팽이", "Snail"],
    ["extra-bug", Bug, "곤충", "Bug"],
    ["extra-paw-print", PawPrint, "반려동물", "Paw Print"],
    ["extra-feather", Feather, "깃털", "Feather"],
    ["extra-flower", Flower, "꽃", "Flower"],
    ["extra-sprout", Sprout, "새싹", "Sprout"],
    ["extra-tree-deciduous", TreeDeciduous, "낙엽수", "Tree Deciduous"],
    ["extra-clover", Clover, "클로버", "Clover"],
    ["extra-cloud", Cloud, "구름", "Cloud"],
    ["extra-cloud-rain", CloudRain, "비", "Cloud Rain"],
    ["extra-cloud-snow", CloudSnow, "눈", "Cloud Snow"],
    ["extra-snowflake", Snowflake, "눈송이", "Snowflake"],
    ["extra-wind", Wind, "바람", "Wind"],
    ["extra-rainbow", Rainbow, "무지개", "Rainbow"],
    ["extra-sun-snow", SunSnow, "계절", "Sun Snow"],
    ["extra-mountain-snow", MountainSnow, "설산", "Mountain Snow"],
    ["extra-earth", Earth, "지구", "Earth"],
    ["extra-orbit", Orbit, "궤도", "Orbit"],
    ["extra-telescope", Telescope, "망원경", "Telescope"],
    ["extra-satellite", Satellite, "인공위성", "Satellite"],
    ["extra-camera-off", CameraOff, "사진휴식", "Camera Off"],
    ["extra-video", Video, "동영상", "Video"],
    ["extra-clapperboard", Clapperboard, "영화촬영", "Clapperboard"],
    ["extra-mic", Mic, "마이크", "Mic"],
    ["extra-drum", Drum, "드럼", "Drum"],
    ["extra-piano", Piano, "피아노", "Piano"],
    ["extra-disc3", Disc3, "음반", "Disc3"],
    ["extra-music2", Music2, "음표", "Music2"],
    ["extra-audio-lines", AudioLines, "오디오", "Audio Lines"],
    ["extra-podcast", Podcast, "팟캐스트", "Podcast"],
    ["extra-paint-bucket", PaintBucket, "색칠", "Paint Bucket"],
    ["extra-brush", Brush, "그림그리기", "Brush"],
    ["extra-origami", Origami, "종이접기", "Origami"],
    ["extra-puzzle", Puzzle, "퍼즐", "Puzzle"],
    ["extra-dices", Dices, "주사위", "Dices"],
    ["extra-spade", Spade, "카드게임", "Spade"],
    ["extra-ferris-wheel", FerrisWheel, "놀이공원", "Ferris Wheel"],
    ["extra-sailboat", Sailboat, "요트", "Sailboat"],
    ["extra-anchor", Anchor, "닻", "Anchor"],
    ["extra-kayak", Kayak, "카약", "Kayak"],
    ["extra-caravan", Caravan, "카라반", "Caravan"],
    ["extra-backpack", Backpack, "배낭", "Backpack"],
    ["extra-luggage", Luggage, "여행가방", "Luggage"],
    ["extra-hotel", Hotel, "호텔", "Hotel"],
    ["extra-building2", Building2, "도시", "Building2"],
    ["extra-castle", Castle, "성", "Castle"],
    ["extra-church", Church, "교회", "Church"],
    ["extra-store", Store, "상점", "Store"],
    ["extra-fuel", Fuel, "주유", "Fuel"],
    ["extra-parking-circle", ParkingCircle, "주차", "Parking Circle"],
    ["extra-traffic-cone", TrafficCone, "도로", "Traffic Cone"],
    ["extra-train-front", TrainFront, "기차앞면", "Train Front"]
  ]
];
