import { symbolExtras } from "./symbolExtras.js";
import {
  BookOpen,
  NotebookPen,
  Pencil,
  GraduationCap,
  Languages,
  Calculator,
  FlaskConical,
  Music,
  Headphones,
  Palette,
  Camera,
  Code,
  Briefcase,
  Mail,
  Phone,
  CalendarDays,
  Clock,
  ListChecks,
  Target,
  Flag,
  Star,
  Heart,
  Activity,
  Dumbbell,
  Bike,
  Footprints,
  Coffee,
  Utensils,
  Droplets,
  Moon,
  Sun,
  House,
  ShoppingBag,
  Wallet,
  Plane,
  Train,
  MapPin,
  Leaf,
  Flower2,
  Lightbulb,
  Sparkles,
  Circle,
  BookText, Library, FileText, FolderOpen, Archive, Clipboard, PenTool,
  Ruler, Microscope, Atom, Brain, Cpu, Monitor, Keyboard, Terminal,
  Presentation, ChartColumn, Search, Printer,
  AlarmClock, Timer, CalendarCheck, CalendarClock, CalendarRange, ListTodo,
  CheckCheck, CircleCheck, SquareCheck, CircleDot, CircleDashed, Repeat,
  RefreshCw, TrendingUp, Trophy, Medal, Award, Bookmark, Bell, Pin,
  Compass, Milestone,
  BedDouble, Bath, ShowerHead, Apple, Salad, Soup, Pill, Stethoscope,
  Cross, ShieldCheck, HandHeart, Smile, BatteryCharging, Sunrise, Sunset,
  WashingMachine, Receipt,
  Car, Bus, TramFront, Ship, Rocket, Map, Navigation, Globe, Mountain,
  Tent, TreePine, Waves, Umbrella, Gamepad2, Film, Tv, Radio, Guitar,
  Paintbrush, Ticket,
} from "lucide-react";

export const symbolGroups = [
  "전체",
  "학습·작업",
  "일정·목표",
  "생활·건강",
  "취미·이동",
];
const groups = [
  [
    ["book", BookOpen, "독서 책"],
    ["note", NotebookPen, "노트 메모"],
    ["pencil", Pencil, "쓰기 연필"],
    ["education", GraduationCap, "교육 공부"],
    ["language", Languages, "언어"],
    ["math", Calculator, "수학 계산"],
    ["science", FlaskConical, "과학 실험"],
    ["code", Code, "코딩 개발"],
    ["work", Briefcase, "업무 일"],
    ["mail", Mail, "이메일"],
    ["idea", Lightbulb, "아이디어"],
    ["book-text", BookText, "교재 문서", "textbook reading"],
    ["library", Library, "도서관 자료", "library books"],
    ["file-text", FileText, "파일 문서", "document file"],
    ["folder", FolderOpen, "폴더 정리", "folder organize"],
    ["archive", Archive, "보관 자료", "archive storage"],
    ["clipboard", Clipboard, "클립보드 기록", "clipboard notes"],
    ["pen-tool", PenTool, "펜 디자인", "pen design"],
    ["ruler", Ruler, "자 측정", "ruler measure"],
    ["microscope", Microscope, "현미경 연구", "microscope research"],
    ["atom", Atom, "원자 물리", "atom physics"],
    ["brain", Brain, "생각 두뇌", "brain thinking"],
    ["cpu", Cpu, "컴퓨터 프로세서", "processor computing"],
    ["monitor", Monitor, "모니터 화면", "desktop screen"],
    ["keyboard", Keyboard, "키보드 입력", "keyboard typing"],
    ["terminal", Terminal, "터미널 명령", "terminal command"],
    ["presentation", Presentation, "발표 수업", "presentation lecture"],
    ["chart", ChartColumn, "차트 분석", "chart analytics"],
    ["search", Search, "검색 조사", "search research"],
    ["printer", Printer, "인쇄 출력", "printer print"],
  ],
  [
    ["calendar", CalendarDays, "달력 일정"],
    ["clock", Clock, "시간"],
    ["checklist", ListChecks, "체크 목록"],
    ["target", Target, "목표"],
    ["flag", Flag, "깃발 마커"],
    ["star", Star, "별 중요"],
    ["sparkles", Sparkles, "반짝임"],
    ["circle", Circle, "원 기본"],
    ["alarm", AlarmClock, "알람 기상", "alarm wake"],
    ["timer", Timer, "타이머 집중", "timer focus"],
    ["calendar-check", CalendarCheck, "예약 완료", "appointment completed"],
    ["calendar-clock", CalendarClock, "예약 시간", "appointment time"],
    ["calendar-range", CalendarRange, "기간 계획", "period schedule"],
    ["todo", ListTodo, "할 일 목록", "todo tasks"],
    ["done", CheckCheck, "완료 확인", "done complete"],
    ["circle-check", CircleCheck, "원 체크", "circle check"],
    ["square-check", SquareCheck, "사각 체크", "square check"],
    ["circle-dot", CircleDot, "선택 표시", "selection dot"],
    ["circle-dashed", CircleDashed, "대기 진행", "pending progress"],
    ["repeat", Repeat, "반복 루틴", "repeat routine"],
    ["refresh", RefreshCw, "갱신 새로고침", "refresh renew"],
    ["growth", TrendingUp, "성장 추세", "growth trend"],
    ["trophy", Trophy, "트로피 성취", "trophy achievement"],
    ["medal", Medal, "메달 수상", "medal reward"],
    ["award", Award, "상 인정", "award certification"],
    ["bookmark", Bookmark, "북마크 저장", "bookmark save"],
    ["bell", Bell, "알림 종", "bell notification"],
    ["pin", Pin, "고정 중요", "pin priority"],
    ["compass", Compass, "방향 나침반", "compass direction"],
    ["milestone", Milestone, "이정표 단계", "milestone step"],
  ],
  [
    ["heart", Heart, "마음 건강"],
    ["activity", Activity, "활동"],
    ["exercise", Dumbbell, "운동"],
    ["walk", Footprints, "걷기 산책"],
    ["coffee", Coffee, "커피 휴식"],
    ["meal", Utensils, "식사"],
    ["water", Droplets, "물"],
    ["moon", Moon, "밤 수면"],
    ["sun", Sun, "아침 햇빛"],
    ["home", House, "집"],
    ["shopping", ShoppingBag, "쇼핑"],
    ["wallet", Wallet, "돈 지출"],
    ["phone", Phone, "전화"],
    ["bed", BedDouble, "침대 잠", "bed sleep"],
    ["bath", Bath, "목욕 욕조", "bath wash"],
    ["shower", ShowerHead, "샤워", "shower"],
    ["apple", Apple, "과일 사과", "fruit apple"],
    ["salad", Salad, "샐러드 채소", "salad vegetable"],
    ["soup", Soup, "국 따뜻한 식사", "soup food"],
    ["pill", Pill, "약 복용", "pill medicine"],
    ["stethoscope", Stethoscope, "진료 병원", "doctor medical"],
    ["cross", Cross, "응급 의료", "first aid medical"],
    ["shield", ShieldCheck, "보호 안전", "shield safety"],
    ["care", HandHeart, "돌봄 배려", "care support"],
    ["smile", Smile, "웃음 기분", "smile mood"],
    ["energy", BatteryCharging, "충전 에너지", "battery energy"],
    ["sunrise", Sunrise, "일출 아침", "sunrise morning"],
    ["sunset", Sunset, "일몰 저녁", "sunset evening"],
    ["laundry", WashingMachine, "세탁 집안일", "laundry chores"],
    ["receipt", Receipt, "영수증 가계부", "receipt expenses"],
  ],
  [
    ["music", Music, "음악"],
    ["headphones", Headphones, "듣기"],
    ["art", Palette, "미술"],
    ["camera", Camera, "사진"],
    ["bike", Bike, "자전거"],
    ["plane", Plane, "여행 비행기"],
    ["train", Train, "기차"],
    ["location", MapPin, "장소"],
    ["leaf", Leaf, "자연"],
    ["flower", Flower2, "꽃"],
    ["car", Car, "자동차 운전", "car driving"],
    ["bus", Bus, "버스", "bus transit"],
    ["tram", TramFront, "전철 지하철", "tram subway metro"],
    ["ship", Ship, "배 항해", "ship sailing"],
    ["rocket", Rocket, "로켓 우주", "rocket space"],
    ["map", Map, "지도 여행", "map travel"],
    ["navigation", Navigation, "길찾기 이동", "navigation route"],
    ["globe", Globe, "세계 해외", "globe world"],
    ["mountain", Mountain, "산 등산", "mountain hiking"],
    ["tent", Tent, "텐트 캠핑", "tent camping"],
    ["tree", TreePine, "나무 숲", "tree forest"],
    ["waves", Waves, "바다 물결", "sea waves"],
    ["umbrella", Umbrella, "우산 비", "umbrella rain"],
    ["game", Gamepad2, "게임 놀이", "game play"],
    ["film", Film, "영화 영상", "film movie"],
    ["tv", Tv, "텔레비전 방송", "tv television"],
    ["radio", Radio, "라디오", "radio"],
    ["guitar", Guitar, "기타 연주", "guitar instrument"],
    ["paintbrush", Paintbrush, "붓 그림", "painting brush"],
    ["ticket", Ticket, "티켓 공연", "ticket concert"],
  ],
];
export const symbols = groups.flatMap((items, i) =>
  [...items, ...symbolExtras[i]].map(([name, Icon, label, keywords = ""]) => ({
    name,
    Icon,
    label,
    group: symbolGroups[i + 1],
    keywords: `${name} ${Icon.displayName || ""} ${keywords}`.toLowerCase(),
  })),
);
export const symbolMap = Object.fromEntries(
  symbols.map((item) => [item.name, item]),
);
export const defaultSymbolColor = "#64748b";
